export enum Brand {
  Enus = 'Enus',
  Albany = 'Albany',
  Dewbauchee = 'Dewbauchee',
  Pegassi = 'Pegassi',
  Coil = 'Coil',
  Obey = 'Obey',
  Benefactor = 'Benefactor',
  Vapid = 'Vapid',
  Canis = 'Canis',
  Ocelot = 'Ocelot',
  Imponte = 'Imponte',
  Gallivanter = 'Gallivanter',
  Declasse = 'Declasse',
  Karin = 'Karin',
  Weeny = 'Weeny',
  Pfister = 'Pfister',
}
