export enum City {
  NewYork = 'New York',
  London = 'London',
  Barcelona = 'Barcelona',
  Tokyo = 'Tokyo',
  Berlin = 'Berlin',
  Dubai = 'Dubai',
  LosAngeles = 'Los Angeles',
  Sydney = 'Sydney',
  CapeTown = 'Cape Town',
  Miami = 'Miami',
  Paris = 'Paris',
  Toronto = 'Toronto',
  Zurich = 'Zurich',
  Rome = 'Rome',
  Moscow = 'Moscow',
  MexicoCity = 'Mexico City',
  BuenosAires = 'Buenos Aires',
  Shanghai = 'Shanghai',
  Seoul = 'Seoul',
  Monaco = 'Monaco',
}

export enum Country {
  UnitedStates = 'United States',
  UnitedKingdom = 'United Kingdom',
  Spain = 'Spain',
  Japan = 'Japan',
  Germany = 'Germany',
  UnitedArabEmirates = 'United Arab Emirates',
  Australia = 'Australia',
  SouthAfrica = 'South Africa',
  France = 'France',
  Canada = 'Canada',
  Switzerland = 'Switzerland',
  Italy = 'Italy',
  Russia = 'Russia',
  Mexico = 'Mexico',
  Argentina = 'Argentina',
  China = 'China',
  SouthKorea = 'South Korea',
  Monaco = 'Monaco',
}
